### PR TITLE
Add developer trace docs

### LINKED ISSUE #68: Developer Documentation: Trace
Using the `trace` module including using it for profiling, logging and debugging

### PR DESCRIPTION
**Pull request by jryates**
fixes #68

### CODE REVIEW

**Comment by jryates** [comment]
I'm not convinced that the TRACE command is helpful. Rather than produce a list of called subroutines (which could be useful) it produces a partial profile.

**Comment by oerc0122** [comment]
> I'm not convinced that the TRACE command is helpful. Rather than produce a list of called subroutines (which could be useful) it produces a partial profile.

It's actually slightly more complicated/advanced than this. 

I'd actually started writing a chunk on the trace module I can merge these two together, if you'd like.

**Comment by jryates** [comment]
Yes - that would be good.

**Comment by oerc0122** [comment]
Sorry, I can't neatly merge it into this one, #77 .

**Comment by jryates** [comment]
superseded by #77

**Pull request closed without merging**
